services:
  - type: web
    name: pgbuddy
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_DEBUG
        value: "0"
      - key: LOG_LEVEL
        value: "info"
    envSecrets:
      - key: PG_BUDDY_SECRET
